FROM python:3.8-bullseye

RUN curl -L https://github.com.cnpmjs.org/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz

CMD ["/wait-for-it/wait-for-it.sh", "douban-crawler-db:5432", "--", "/root/migrate.sh"]
