CREATE TABLE IF NOT EXISTS books (
  id bigserial PRIMARY KEY,
  title text DEFAULT '',
  subtitle text DEFAULT '',
  author text DEFAULT '',
  author_url text DEFAULT '',
  author_intro text DEFAULT '',
  publisher text DEFAULT '',
  published_at timestamp without time zone DEFAULT NULL,
  original_title text DEFAULT '',
  translator text DEFAULT '',
  producer text DEFAULT '',
  series text DEFAULT '',
  price text DEFAULT '',
  isbn text DEFAULT '',
  pages int DEFAULT 0,
  bookbinding text DEFAULT '',
  book_intro text DEFAULT '',
  toc text DEFAULT '',
  rating real DEFAULT 0.0,
  rating_count int DEFAULT 0,
  cover_img_url text DEFAULT '',
  origin text DEFAULT '',
  origin_id text DEFAULT '',
  origin_url text UNIQUE DEFAULT '',
  crawled boolean DEFAULT False,
  created_at timestamp without time zone default (now() at time zone 'utc'),
  updated_at timestamp without time zone default (now() at time zone 'utc'),
  deleted_at timestamp without time zone default NULL
);

