CREATE TABLE IF NOT EXISTS books (
  id bigserial PRIMARY KEY,
  title text DEFAULT '',
  subtitle text DEFAULT '',
  author text DEFAULT '',
  publisher text DEFAULT '',
  published_at timestamp without time zone DEFAULT NULL,
  price text DEFAULT '',
  isbn text DEFAULT '',
  pages int DEFAULT 0,
  bookbinding text DEFAULT '',
  book_intro text DEFAULT '',
  author_intro text DEFAULT '',
  toc text DEFAULT '',
  rating int DEFAULT 0,
  rating_count int DEFAULT 0,
  cover_img_url text DEFAULT '',
  origin text DEFAULT '',
  origin_id text DEFAULT '',
  origin_url text UNIQUE DEFAULT '',
  created_at timestamp without time zone default (now() at time zone 'utc'),
  updated_at timestamp without time zone default (now() at time zone 'utc'),
  deleted_at timestamp without time zone default NULL
);

